# Generated by Django 5.2.8 on 2025-12-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/banners/', verbose_name='баннер')),
                ('title_en', models.CharField(max_length=255, verbose_name='Самый большой текст в баннере (en)')),
                ('title_kg', models.CharField(max_length=255, verbose_name='Самый большой текст в баннере (kg)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Самый большой текст в баннере (ru)')),
                ('idea_en', models.CharField(max_length=255, verbose_name='Идея баннера (en)')),
                ('idea_kg', models.CharField(max_length=255, verbose_name='Идея  баннера (kg)')),
                ('idea_ru', models.CharField(max_length=255, verbose_name='Идея  баннера (ru)')),
                ('desctip_en', models.CharField(max_length=255, verbose_name='Описание баннера (en)')),
                ('desctip_kg', models.CharField(max_length=255, verbose_name='Описание баннера (kg)')),
                ('desctip_ru', models.CharField(max_length=255, verbose_name='Описание баннера (ru)')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
