# Generated by Django 5.2.8 on 2025-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Главный текст баннера (en)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_kg',
            field=models.CharField(max_length=255, verbose_name='Главный текст баннера (kg)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Главный текст баннерали (ru)'),
        ),
    ]
