# Generated by Django 5.2.8 on 2025-12-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banners', '0002_alter_banner_title_en_alter_banner_title_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка для кнопки(необязательно)'),
        ),
    ]
