# Generated by Django 5.2.8 on 2025-12-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Banners", "0003_banner_link_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="desctip_en",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="desctip_kg",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="desctip_ru",
        ),
        migrations.AlterField(
            model_name="banner",
            name="idea_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Идея баннера (en)"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="idea_kg",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Идея  баннера (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="idea_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Идея  баннера (ru)"
            ),
        ),
    ]

# Generated by Django 5.2.8 on 2025-12-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banners', '0003_banner_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='desctip_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='desctip_kg',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='desctip_ru',
        ),
        migrations.AlterField(
            model_name='banner',
            name='idea_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идея баннера (en)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='idea_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идея  баннера (kg)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='idea_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идея  баннера (ru)'),
        ),
    ]
