# Generated by Django 5.2.8 on 2025-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='contacts/logos/')),
                ('name_en', models.CharField(max_length=255, verbose_name='название(en)')),
                ('name_kg', models.CharField(max_length=255, verbose_name='название(kg)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='название(ru)')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('work_time_en', models.CharField(max_length=255, verbose_name='рабочее время(en)')),
                ('work_time_kg', models.CharField(max_length=255, verbose_name='рабочее время(kg)')),
                ('work_time_ru', models.CharField(max_length=255, verbose_name='рабочее время(ru)')),
                ('tg_link', models.URLField(blank=True, null=True, verbose_name='ссылка на телеграм')),
                ('wb_link', models.URLField(blank=True, null=True, verbose_name='ссылка на whatsapp')),
                ('ins_link', models.URLField(blank=True, null=True, verbose_name='ссылка на instagram')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
