# Generated by Django 5.2.8 on 2025-12-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_alter_gallery_options_remove_gallery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (en)'),
        ),
        migrations.AddField(
            model_name='photos',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (kg)'),
        ),
        migrations.AddField(
            model_name='photos',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (ru)'),
        ),
    ]
