# Generated by Django 5.2.8 on 2025-12-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_photos_title_en_photos_title_kg_photos_title_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['id'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
        migrations.RemoveField(
            model_name='photos',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='title_kg',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (en)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (kg)'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (ru)'),
        ),
    ]
