# Generated by Django 5.2.8 on 2025-11-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FactCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(upload_to="fact_cards/", verbose_name="Иконка"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Заголовок (EN)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Заголовок (RU)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=255, verbose_name="Заголовок (KG)"),
                ),
                ("description_en", models.TextField(verbose_name="Описание (EN)")),
                ("description_ru", models.TextField(verbose_name="Описание (RU)")),
                ("description_kg", models.TextField(verbose_name="Описание (KG)")),
            ],
            options={
                "verbose_name": "Факт-карта",
                "verbose_name_plural": "Факт-карты",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FactDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detail_en",
                    models.CharField(max_length=255, verbose_name="Деталь (EN)"),
                ),
                (
                    "detail_ru",
                    models.CharField(max_length=255, verbose_name="Деталь (RU)"),
                ),
                (
                    "detail_kg",
                    models.CharField(max_length=255, verbose_name="Деталь (KG)"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="about_us.factcard",
                        verbose_name="Факт-карта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Деталь факта",
                "verbose_name_plural": "Детали фактов",
                "ordering": ["id"],
            },
        ),
    ]
