# Generated by Django 5.2.8 on 2025-11-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="leaders/", verbose_name="Фото")),
                ("name_ru", models.CharField(max_length=255, verbose_name="ФИО (RU)")),
                ("name_en", models.CharField(max_length=255, verbose_name="ФИО (EN)")),
                ("name_kg", models.CharField(max_length=255, verbose_name="ФИО (KG)")),
                (
                    "position_ru",
                    models.CharField(max_length=255, verbose_name="Должность (RU)"),
                ),
                (
                    "position_en",
                    models.CharField(max_length=255, verbose_name="Должность (EN)"),
                ),
                (
                    "position_kg",
                    models.CharField(max_length=255, verbose_name="Должность (KG)"),
                ),
                ("bio_kg", models.TextField(verbose_name="Биография (KG)")),
                ("bio_ru", models.TextField(verbose_name="Биография (RU)")),
                ("bio_en", models.TextField(verbose_name="Биография (EN)")),
                ("achievements_kg", models.JSONField(verbose_name="Достижения (KG)")),
                ("achievements_ru", models.JSONField(verbose_name="Достижения (RU)")),
                ("achievements_en", models.JSONField(verbose_name="Достижения (EN)")),
                ("education_kg", models.JSONField(verbose_name="Образование (KG)")),
                ("education_ru", models.JSONField(verbose_name="Образование (RU)")),
                ("education_en", models.JSONField(verbose_name="Образование (EN)")),
            ],
            options={
                "verbose_name": "Лидер",
                "verbose_name_plural": "Лидеры",
                "ordering": ["id"],
            },
        ),
    ]
