# Generated by Django 5.2.8 on 2025-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_leader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['id'], 'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководство'},
        ),
        migrations.AddField(
            model_name='factcard',
            name='detail_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Деталь (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factcard',
            name='detail_kg',
            field=models.CharField(default=1, max_length=255, verbose_name='Деталь (KG)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factcard',
            name='detail_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Деталь (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factcard',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='Является баннером?'),
        ),
        migrations.AddField(
            model_name='factcard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fact_cards/banners/', verbose_name='Фото баннера'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='achievements_en',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Достижения (EN) - необязательно заполнять'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='achievements_kg',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Достижения (KG) - необязательно заполнять'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='achievements_ru',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Достижения (RU) - необязательно заполнять'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Биография (EN) - необязательно заполнять'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='bio_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Биография (KG) - необязательно заполнять'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Биография (RU) - необязательно заполнять'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='education_en',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Образование (EN) - необязательно заполнять'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='education_kg',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Образование (KG) - необязательно заполнять'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='education_ru',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Образование (RU) - необязательно заполнять'),
        ),
        migrations.DeleteModel(
            name='FactDetail',
        ),
    ]
