# Generated by Django 5.2.8 on 2025-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0003_alter_leader_options_factcard_detail_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_ru", models.TextField()),
                ("description_en", models.TextField()),
                ("description_kg", models.TextField()),
                ("image", models.ImageField(upload_to="history/")),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Историческая веха",
                "verbose_name_plural": "История",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="factcard",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fact_cards/banners/",
                verbose_name="Вставьте фото только если этот факт должен быть баннером",
            ),
        ),
    ]
