# Generated by Django 5.2.8 on 2025-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0004_history_alter_factcard_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="history/"),
        ),
    ]
