# Generated by Django 5.2.8 on 2025-12-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0005_alter_history_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Slug (URL)"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="subsidiaries/logos/", verbose_name="Логотип"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="Название (EN)"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Название (RU)"),
                ),
                (
                    "name_kg",
                    models.CharField(max_length=255, verbose_name="Название (KG)"),
                ),
                (
                    "short_description_en",
                    models.TextField(verbose_name="Краткое описание (EN)"),
                ),
                (
                    "short_description_ru",
                    models.TextField(verbose_name="Краткое описание (RU)"),
                ),
                (
                    "short_description_kg",
                    models.TextField(verbose_name="Краткое описание (KG)"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Полное описание (EN)"),
                ),
                (
                    "description_ru",
                    models.TextField(verbose_name="Полное описание (RU)"),
                ),
                (
                    "description_kg",
                    models.TextField(verbose_name="Полное описание (KG)"),
                ),
                ("founded_year", models.IntegerField(verbose_name="Год основания")),
                (
                    "achievements_en",
                    models.JSONField(
                        default=list,
                        help_text="Список достижений на английском",
                        verbose_name="Достижения (EN)",
                    ),
                ),
                (
                    "achievements_ru",
                    models.JSONField(
                        default=list,
                        help_text="Список достижений на русском",
                        verbose_name="Достижения (RU)",
                    ),
                ),
                (
                    "achievements_kg",
                    models.JSONField(
                        default=list,
                        help_text="Список достижений на кыргызском",
                        verbose_name="Достижения (KG)",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=500, verbose_name="Адрес"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Структурное подразделение",
                "verbose_name_plural": "Структура организации",
                "ordering": ["order", "name_ru"],
            },
        ),
    ]
