# Generated by Django 5.2.8 on 2025-12-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0006_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['order', 'name_ru'], 'verbose_name': 'Структурное подразделение', 'verbose_name_plural': 'Структура'},
        ),
    ]
