# Generated by Django 5.2.8 on 2025-12-17 09:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0007_alter_structure_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="achievements_en",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="achievements_kg",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="achievements_ru",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="founded_year",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="short_description_en",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="short_description_kg",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="short_description_ru",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="structure",
            name="website",
        ),
        migrations.AlterField(
            model_name="structure",
            name="description_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="structure",
            name="description_kg",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="structure",
            name="description_ru",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
