# Generated by Django 5.2.8 on 2025-12-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0010_alter_structure_founded_year_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factcard',
            name='detail_en',
        ),
        migrations.RemoveField(
            model_name='factcard',
            name='detail_kg',
        ),
        migrations.RemoveField(
            model_name='factcard',
            name='detail_ru',
        ),
    ]
