# Generated by Django 5.2.8 on 2025-12-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0011_remove_factcard_detail_en_remove_factcard_detail_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factcard',
            name='icon',
        ),
        migrations.AlterField(
            model_name='factcard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fact_cards/', verbose_name='Фото'),
        ),
    ]
