# Generated by Django 5.2.8 on 2025-12-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_remove_structure_achievements_en_and_more'),
        ('about_us', '0012_remove_factcard_icon_alter_factcard_photo'),
    ]

    operations = [
    ]
