# Generated by Django 5.2.8 on 2025-12-18 07:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0013_merge_20251217_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='aspect_ratio',
            field=models.CharField(choices=[('square', 'Квадрат (1:1)'), ('portrait', 'Портрет (3:4)'), ('landscape', 'Пейзаж (4:3)'), ('wide', 'Широкий (16:9)'), ('tall', 'Высокий (9:16)')], default='square', max_length=20, verbose_name='Пропорции логотипа'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description_kg',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
