# Generated by Django 5.2.8 on 2025-12-25 09:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0014_structure_aspect_ratio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="description_en",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="description_kg",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description (KG)"
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="description_ru",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Description (RU)"
            ),
        ),
    ]
