# Generated by Django 5.1.2 on 2025-12-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0005_alter_news_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/photos/', verbose_name='Фото')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, verbose_name='Alt текст (EN)')),
                ('alt_text_ru', models.CharField(blank=True, max_length=255, verbose_name='Alt текст (RU)')),
                ('alt_text_kg', models.CharField(blank=True, max_length=255, verbose_name='Alt текст (KG)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='presscentre.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фото новости',
                'verbose_name_plural': 'Фото новостей',
                'ordering': ['order', 'id'],
            },
        ),
    ]
