# Generated by Django 5.2.8 on 2025-12-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0008_publicationcategory_alter_publication_category'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE presscentre_news ADD COLUMN IF NOT EXISTS aspect_ratio VARCHAR(20) DEFAULT 'landscape' NOT NULL;",
            reverse_sql="ALTER TABLE presscentre_news DROP COLUMN IF EXISTS aspect_ratio;",
        ),
    ]
