# Generated by Django 5.2.8 on 2025-12-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0008_publicationcategory_alter_publication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='aspect_ratio',
            field=models.CharField(choices=[('square', 'Квадрат (1:1)'), ('portrait', 'Портрет (3:4)'), ('landscape', 'Пейзаж (4:3)'), ('wide', 'Широкий (16:9)'), ('tall', 'Высокий (9:16)')], default='landscape', max_length=20, verbose_name='Пропорции изображения'),
        ),
    ]
