# Generated by Django 5.2.8 on 2025-12-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0009_news_aspect_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='aspect_ratio',
        ),
    ]
