# Generated by Django 5.2.8 on 2025-12-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0009_news_aspect_ratio'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE presscentre_news DROP COLUMN IF EXISTS aspect_ratio;",
            reverse_sql="ALTER TABLE presscentre_news ADD COLUMN IF NOT EXISTS aspect_ratio VARCHAR(20) DEFAULT 'landscape' NOT NULL;",
        ),
    ]
