# Generated by Django 5.2.8 on 2025-12-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0010_remove_news_aspect_ratio'),
    ]

    operations = [
    ]
