# Generated by Django 5.2.8 on 2025-12-19 10:26

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0010_remove_news_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1200x630', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для обрезки. Рекомендуемый размер: 1200x630px', hide_image_field=False, size_warning=True, verbose_name='Обрезка изображения'),
        ),
    ]
