# Generated by Django 5.2.8 on 2025-12-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_alter_gallery_options_remove_photos_title_en_and_more'),
        ('presscentre', '0011_newsphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='Gallery.gallery', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: (16:9)', null=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
