# Generated by Django 5.2.8 on 2025-12-19 10:29

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0011_news_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1200x675', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для обрезки. Рекомендуемый размер: (16:9)', hide_image_field=False, size_warning=True, verbose_name='Обрезка изображения'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: (16:9)', null=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
