# Generated by Django 5.2.8 on 2025-12-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0011_add_news_gallery'),
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='gallery',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='news',
                to='Gallery.gallery',
                verbose_name='Галерея',
                help_text='Дополнительные фотографии для новости',
            ),
        ),
    ]
