# Generated by Django 5.2.8 on 2025-12-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0012_publication_gallery_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cropping',
            field=models.CharField(blank=True, help_text='Координаты обрезки изображения (JSON формат)', max_length=255, null=True, verbose_name='Обрезка изображения'),
        ),
    ]
