# Generated by Django 5.2.8 on 2025-12-19 10:34

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0012_alter_news_cropping_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='aspect_ratio',
            field=models.CharField(choices=[('16x9', '16:9 (Широкоформатное)'), ('4x3', '4:3 (Стандартное)'), ('1x1', '1:1 (Квадратное)'), ('3x4', '3:4 (Портретное)'), ('9x16', '9:16 (Вертикальное)')], default='16x9', help_text='Выберите желаемое соотношение сторон для изображения', max_length=20, verbose_name='Соотношение сторон'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1200x675', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Выберите область для обрезки. Перетащите или измените размер рамки для выбора нужной области.', hide_image_field=False, size_warning=True, verbose_name='Обрезка изображения'),
        ),
    ]
