# Generated by Django 5.2.8 on 2025-12-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0012_fix_news_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='gallery',
        ),
    ]
