# Generated by Django 5.2.8 on 2025-12-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0012_publication_gallery_alter_news_image'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE presscentre_news ADD COLUMN IF NOT EXISTS cropping VARCHAR(255) NULL;",
            reverse_sql="ALTER TABLE presscentre_news DROP COLUMN IF EXISTS cropping;",
        ),
    ]
