# Generated by Django 5.2.8 on 2025-12-20 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0011_news_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='aspect_ratio',
        ),
    ]
