# Generated by Django 5.2.8 on 2025-12-20 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_alter_gallery_options_remove_photos_title_en_and_more'),
        ('presscentre', '0013_remove_news_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='Gallery.gallery', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: (16:9)', null=True, upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/photos/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения фото', verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='presscentre.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фото новости',
                'verbose_name_plural': 'Фото новости',
                'ordering': ['order', 'id'],
            },
        ),
    ]
