# Generated by Django 5.2.8 on 2025-12-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0013_news_cropping'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE presscentre_news ALTER COLUMN cropping DROP NOT NULL;",
            reverse_sql="ALTER TABLE presscentre_news ALTER COLUMN cropping SET NOT NULL;",
        ),
    ]
