# Generated by Django 5.2.8 on 2025-12-22 05:36

from django.db import migrations, connection


def remove_aspect_ratio_column(apps, schema_editor):
    """Remove aspect_ratio column if it exists"""
    with connection.cursor() as cursor:
        # Check database vendor
        if connection.vendor == 'postgresql':
            cursor.execute("ALTER TABLE presscentre_news DROP COLUMN IF EXISTS aspect_ratio CASCADE;")
        elif connection.vendor == 'sqlite':
            # SQLite doesn't support DROP COLUMN IF EXISTS, check if column exists first
            cursor.execute("PRAGMA table_info(presscentre_news);")
            columns = [row[1] for row in cursor.fetchall()]
            if 'aspect_ratio' in columns:
                # SQLite doesn't support DROP COLUMN easily, we need to recreate the table
                # But since we're migrating forward, we can just skip for SQLite (dev db)
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0014_alter_news_cropping_nullable'),
    ]

    operations = [
        migrations.RunPython(remove_aspect_ratio_column, migrations.RunPython.noop),
    ]
