# Generated by Django 5.2.8 on 2025-12-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0010_remove_news_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='aspect_ratio',
            field=models.CharField(choices=[('16x9', '16:9 (Широкоформатное)'), ('4x3', '4:3 (Стандартное)'), ('1x1', '1:1 (Квадратное)'), ('3x4', '3:4 (Портретное)'), ('9x16', '9:16 (Вертикальное)')], default='16x9', help_text='Выберите желаемое соотношение сторон для изображения', max_length=20, verbose_name='Соотношение сторон'),
        ),
    ]
