# Generated by Django 5.2.8 on 2025-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presscentre", "0015_remove_aspect_ratio_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="cropping",
            field=models.CharField(
                blank=True,
                help_text="Координаты обрезки изображения (JSON формат)",
                max_length=255,
                null=True,
                verbose_name="Обрезка изображения",
            ),
        ),
    ]
