# Generated by Django 5.2.8 on 2025-12-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0014_remove_news_aspect_ratio'),
        ('presscentre', '0015_news_aspect_ratio'),
    ]

    operations = [
    ]
