# Generated by Django 5.2.8 on 2025-12-20 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0004_alter_gallery_options_remove_photos_title_en_and_more'),
        ('presscentre', '0016_publication_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='gallery',
        ),
        migrations.AddField(
            model_name='news',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='Gallery.gallery', verbose_name='Галерея'),
        ),
    ]
