# Generated by Django 5.2.8 on 2025-12-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presscentre", "0015_remove_aspect_ratio_column"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
        migrations.RemoveField(
            model_name="publication",
            name="author",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="category",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="description_kg",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="gallery",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="published_at",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="short_description_en",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="short_description_kg",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="short_description_ru",
        ),
        migrations.AddField(
            model_name="publication",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка"
            ),
        ),
    ]
