# Generated by Django 5.2.8 on 2025-12-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0015_news_aspect_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cropping',
        ),
    ]
