# Generated by Django 5.2.8 on 2025-12-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0017_alter_publication_options_remove_publication_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationCategory',
        ),
    ]
