# Generated by Django 5.2.8 on 2025-12-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0014_remove_news_aspect_ratio'),
        ('presscentre', '0016_publication_gallery'),
        ('presscentre', '0017_remove_publication_gallery_news_gallery'),
        ('presscentre', '0018_remove_news_cropping'),
    ]

    operations = [
    ]
