# Generated by Django 5.2.8 on 2025-12-27 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0006_newsphoto'),
        ('presscentre', '0018_remove_publication_category'),
    ]

    operations = [
    ]
