# Generated by Django 5.2.8 on 2025-12-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0018_remove_publication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cropping',
            field=models.CharField(blank=True, help_text='Координаты обрезки изображения (JSON формат)', max_length=255, null=True, verbose_name='Обрезка изображения'),
        ),
    ]
