# Generated by Django 5.2.8 on 2025-12-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0018_remove_publication_category'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE presscentre_news ADD COLUMN IF NOT EXISTS cropping VARCHAR(255) NULL;",
            reverse_sql="ALTER TABLE presscentre_news DROP COLUMN IF EXISTS cropping;",
        ),
    ]
